### ISSUE TITLE
Disable bot reaction on «mark-word» if I talk to him

### ISSUE THREAD

**Issue by conformist-mw** [tune-it/jplbot#10]
As it is knowns bot react to «mark-word» such as nickname or predefined word like ubuntu, perl. But it doesn't need when I speak to bot for memorize phrase. For example:
[20:24:11]conformist: AimBot: just test with mark-word like ubuntu perl
[20:24:11] AimBot: убунта нинужна >_<
It can be fixed?

**Comment by zhmylove** [comment]
Fixed in b2a1d15058fb91853a9bab749662f24ded84d7bc
