### ISSUE TITLE
Wrong message

### ISSUE THREAD

**Issue by kirillDanshin** [tune-it/jplbot#14]
`sudo apt-get install ...` should not send `sudo нинужно >_<`. We can send something else.

**Comment by zhmylove** [comment]
What exactly do you prefer to see instead of that message?

**Comment by kirillDanshin** [comment]
@zhmylove anything else? maybe, s/sudo/apt-get/?

**Comment by zhmylove** [comment]
@kirillDanshin at the present moment the bot has a reaction on the keyword 'sudo'.
Literally:

``` perl
when (/sudo/) {return (1, 0, "sudo нинужно >_<") if int(2*rand)};
```

Do you want to change the pattern into `/sudo\s*(\S+)/` and send a message `"$1 нинужно >_<"` ? 

Or maybe the correct solution is to divide this cases and adjust their probabilities:

``` perl
when (/sudo/) {
 return (1, 0, "sudo нинужно >_<") if int(1.5*rand);
 return (1, 0, "apt-get для школьников >_<") if int(2*rand) && /apt-get/;
}
```

On the other hand we can diversify 'sudo' reactions:

``` perl
return (1, 0, "sudo нинужно >_<") if int(1.5*rand);
return (1, 0, "sudo для слабых!") if int(2*rand)};
```

**Comment by kirillDanshin** [comment]
I think we can do something like

``` perl
when (/sudo\s*/) {
  return (1, 0, "а слабо без sudo?") if int(1.3*rand);
}
when (/(sudo)|sudo(?:\s+(\S+))?/) {
  return (1, 0, "$1 нинужно >_<") if int(1.5*rand);
  return (1, 0, "$1 для слабых!") if int(1.6*rand);
  return (1, 0, "$1 для школоты >_<") if int(2*rand);
}
```

**Comment by zhmylove** [comment]
@kirillDanshin Please check out 8a95f628210ed2904baa67527bac0b0298751ed3
Is it what have you requested?

**Comment by kirillDanshin** [comment]
@zhmylove yep :+1: 
![2016-07-04 19 27 18](https://cloud.githubusercontent.com/assets/9026581/16566476/7e5bb5c4-421d-11e6-89c4-14d75428c0e2.png)

**Comment by zhmylove** [comment]
@kirillDanshin thank you for your feedback! As I can see, the issue can be closed.
Kind regards, Sergey Zhmylove.

**Comment by kirillDanshin** [comment]
@zhmylove thanks :)
