### ISSUE TITLE
Pikabu & vk title 

### ISSUE THREAD

**Issue by refeaime** [tune-it/jplbot#2]
Trying to get tittle from pikabu pages, server comeback with error 500
" telnet m.pikabu.ru 80
Trying 91.228.155.94...
Connected to m.pikabu.ru.
Escape character is '^]'.
HEAD /story/importozameshchenie_3908711 HTTP/1.1
Host: m.pikabu.ru
Connection closed by foreign host. "
For example.

**Comment by zhmylove** [comment]
Issue resolved in cbfe81d991fb094233e1ca9277d7b9ff00a14fe7
