### ISSUE TITLE
Pointy brackets in message body

### ISSUE THREAD

**Issue by conformist-mw** [tune-it/jplbot#36]
In message body bot replace pointy brackets `<` and `>` with `&lt` and `&gt` respectively.

**Comment by zhmylove** [comment]
Keeping this problem in mind since https://github.com/zhmylove/jxtg release. 
This issue closed due to invalid project.
Fixed the issue in https://github.com/zhmylove/jxtg/commit/4e4cc418184ced7f98bfee9a8f560a55c998eaba
