### ISSUE TITLE
цитаты в sh шутках

### ISSUE THREAD

**Issue by nullawhale** [tune-it/jplbot#42]
&quot; instead of "

**Comment by nullawhale** [comment]
Snick: Сейчас ехал по улице и увидел магазин &quot;Фейерверки-Евроинтим&quot;. Интересно, что там продают? =)
Vovik@work: Мухахаха )
Snick: Анальные хлопушки из германии, наверно =)

**Comment by nullawhale** [comment]
& quot;

**Comment by zhmylove** [comment]
Closed by @csepanda
