### ISSUE TITLE
Бендер "Сгибальщик" Родригез

### ISSUE THREAD

**Issue by vankosa** [tune-it/jplbot#48]
Добрый день, я с деревни с руссколокализованной винды, поэтому пишу на русском языке

Прошу включить ответ бота в случайном порядке (то бишь не каждый раз) на фразу "кожаные мешки" или "кожаные ублюдки" фразы в стиле Бендера "Сгибальщика" Родригеза, например, "Убить всех человеков" или "Поцелуй меня в мой блестящий зад"

Спасибо

**Comment by zhmylove** [comment]
Implemented in b3553c94debb1749b00ee67f3c159ce282d7a299
