### ISSUE TITLE
Bot addressed message memory

### ISSUE THREAD

**Issue by conformist-mw** [tune-it/jplbot#8]
In one conference I've seen the bot which accept phrase that toward to him like:
[time] conformist: bot: hi there!
and remember it into the file (or database, IDK), and if I speech to him, of simple cast like bot in chat — it responds with random phrase from db. It's funny and I'd like to add this functionality to our bot!
Cheers!

**Comment by zhmylove** [comment]
Added an implementation in 7127ccf903da48ec5333fcba524c64ed993b2a6a
Waiting for an aprobation.

**Comment by zhmylove** [comment]
Finalized in b58e46c5e06df88e07d248df1880acd4f09060e6
